[package]
name = "tack"
version = "0.1.0-beta"
edition = "2024"
license = "LGPL-3.0-only"

[profile.release]
strip = false
opt-level = 3
lto = true
codegen-units = 1
debug = "line-tables-only"

[features]
rustls = ["curl/rustls", "dep:openssl-probe"]

[dependencies]
jni = { version = "0.22.4", features = ["invocation"] }
java-locator = "0.1.9"
qbsdiff = "1.4.4"

sha2 = "0.11.0"
digest-io = "0.1.0"
thiserror = "2.0.19"
zip = "8.6.0"
hex = "0.4.3"
os_pipe = "1.2.3"

serde = { version = "1.0.229", features = ["derive"] }
postcard = "1.1.3"

indoc = "2.0.7"

[target.'cfg(not(target_os = "linux"))'.dependencies]
nyquest = { version = "0.4.0", features = ["blocking-stream"] }
nyquest-preset = { version = "0.4.0", features = ["blocking-stream"] }

[target.'cfg(target_os = "linux")'.dependencies]
curl = "0.4.50"
openssl-probe = { version = "0.2.1", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.10.1"

[build-dependencies]
chrono = { version = "0.4.45", features = ["now"] }

[target.'cfg(target_os = "linux")'.build-dependencies]
pkg-config = "0.3.33"
